package cabd;


/**
* cabd/CalculatorPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Suma.idl
* Wednesday, April 11, 2018 10:42:28 PM VET
*/

public abstract class CalculatorPOA extends org.omg.PortableServer.Servant
 implements cabd.CalculatorOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("sumar", new java.lang.Integer (0));
    _methods.put ("restar", new java.lang.Integer (1));
    _methods.put ("multiplicar", new java.lang.Integer (2));
    _methods.put ("dividir", new java.lang.Integer (3));
    _methods.put ("shutdown", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // cabd/Calculator/sumar
       {
         int a = in.read_long ();
         int b = in.read_long ();
         int $result = (int)0;
         $result = this.sumar (a, b);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // cabd/Calculator/restar
       {
         int a = in.read_long ();
         int b = in.read_long ();
         int $result = (int)0;
         $result = this.restar (a, b);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 2:  // cabd/Calculator/multiplicar
       {
         int a = in.read_long ();
         int b = in.read_long ();
         int $result = (int)0;
         $result = this.multiplicar (a, b);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 3:  // cabd/Calculator/dividir
       {
         int a = in.read_long ();
         int b = in.read_long ();
         int $result = (int)0;
         $result = this.dividir (a, b);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 4:  // cabd/Calculator/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:cabd/Calculator:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Calculator _this() 
  {
    return CalculatorHelper.narrow(
    super._this_object());
  }

  public Calculator _this(org.omg.CORBA.ORB orb) 
  {
    return CalculatorHelper.narrow(
    super._this_object(orb));
  }


} // class CalculatorPOA
