package cabd;


/**
* cabd/Calculator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Suma.idl
* Wednesday, April 11, 2018 10:42:28 PM VET
*/

public interface Calculator extends CalculatorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Calculator
