package cabd;


/**
* cabd/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Suma.idl
* Wednesday, April 11, 2018 10:42:28 PM VET
*/

public interface CalculatorOperations 
{
  int sumar (int a, int b);
  int restar (int a, int b);
  int multiplicar (int a, int b);
  int dividir (int a, int b);
  void shutdown ();
} // interface CalculatorOperations
